import type { CaptionPositionIndex, PresetCategory } from "./types";

export interface ViralPreset {
  id: string;
  num: number;
  name: string;
  category: PresetCategory;
  tag: string;
  whatItLooksLike: string;
  description: string;
  fontSize: number;
  wordsPerGroup: 1 | 2 | 3;
  bounceScale: number;
  yOffset: number;
  baseColor: string;
  highlightColor: string;
  strokeWidth: number;
  strokeColor: string;
  posIndex: CaptionPositionIndex;
  reveal: boolean;
  highlight: boolean;
  pop: boolean;
  shadow: boolean;
  font: string;
  animMode: string;
  previewBgGradient: string;
  accentBadge: string;
  previewStyleClass: string;
}

const CLASSIC_PRESETS: ViralPreset[] = [
  // ==========================================
  // TIKTOK / REELS / SHORTS (#51 - #65)
  // ==========================================
  {
    id: "single-word-center",
    num: 51,
    name: "Single Word Center",
    category: "TikTok / Reels / Shorts",
    tag: "CENTER JUMP",
    whatItLooksLike: "One giant word at a time, dead center, hard cuts",
    description: "Ultra-high retention 1-word focus directly in center view. Maximum engagement for fast speakers.",
    fontSize: 92,
    wordsPerGroup: 1,
    bounceScale: 30,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FFE600",
    strokeWidth: 8,
    strokeColor: "#000000",
    posIndex: 2, // Center
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "single-word",
    previewBgGradient: "from-yellow-500/20 via-surface-container to-transparent",
    accentBadge: "bg-yellow-400 text-black",
    previewStyleClass: "preset-anim-center-jump",
  },
  {
    id: "underline-swipe",
    num: 52,
    name: "Underline Swipe",
    category: "TikTok / Reels / Shorts",
    tag: "ACCENT SWIPE",
    whatItLooksLike: "Line draws under the active word left → right",
    description: "Sleek animated horizontal underline that wipes under active spoken words with zero latency.",
    fontSize: 76,
    wordsPerGroup: 2,
    bounceScale: 15,
    yOffset: -110,
    baseColor: "#FFFFFF",
    highlightColor: "#D0BCFF",
    strokeWidth: 4,
    strokeColor: "#111111",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "underline",
    previewBgGradient: "from-secondary/20 via-surface-container to-transparent",
    accentBadge: "bg-secondary text-on-secondary",
    previewStyleClass: "preset-anim-underline",
  },
  {
    id: "rotate-in-words",
    num: 53,
    name: "Rotate In Words",
    category: "TikTok / Reels / Shorts",
    tag: "TILT OVERSHOOT",
    whatItLooksLike: "Each word spins in from -15° with overshoot",
    description: "Playful dynamic rotation springing from -15 degrees with snappy physics-based settling.",
    fontSize: 80,
    wordsPerGroup: 2,
    bounceScale: 25,
    yOffset: -120,
    baseColor: "#FFFFFF",
    highlightColor: "#FF5A36",
    strokeWidth: 6,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "rotate",
    previewBgGradient: "from-orange-500/20 via-surface-container to-transparent",
    accentBadge: "bg-orange-500 text-white",
    previewStyleClass: "preset-anim-rotate",
  },
  {
    id: "stroke-to-fill",
    num: 54,
    name: "Stroke to Fill",
    category: "TikTok / Reels / Shorts",
    tag: "HOLLOW INVERT",
    whatItLooksLike: "Outline text fills with color when spoken",
    description: "Hollow wireframe words that ignite with solid saturated color the moment they are articulated.",
    fontSize: 78,
    wordsPerGroup: 2,
    bounceScale: 18,
    yOffset: -115,
    baseColor: "#E5E2E1",
    highlightColor: "#00F0FF",
    strokeWidth: 6,
    strokeColor: "#00F0FF",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: false,
    font: "Arial-BoldMT",
    animMode: "stroke-fill",
    previewBgGradient: "from-cyan-500/20 via-surface-container to-transparent",
    accentBadge: "bg-cyan-400 text-black",
    previewStyleClass: "preset-anim-stroke-fill",
  },
  {
    id: "sticker-caption",
    num: 55,
    name: "Sticker Caption",
    category: "TikTok / Reels / Shorts",
    tag: "STICKER POP",
    whatItLooksLike: "Text in white \"sticker\" shapes with a slight tilt",
    description: "Trendy Y2K paper sticker cutout aesthetic with bold black text on bright white rounded slabs.",
    fontSize: 72,
    wordsPerGroup: 2,
    bounceScale: 22,
    yOffset: -130,
    baseColor: "#111111",
    highlightColor: "#1000A9",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "sticker",
    previewBgGradient: "from-white/20 via-surface-container to-transparent",
    accentBadge: "bg-white text-black font-bold",
    previewStyleClass: "preset-anim-sticker",
  },
  {
    id: "squash-and-stretch",
    num: 56,
    name: "Squash & Stretch",
    category: "TikTok / Reels / Shorts",
    tag: "RUBBER BOUNCE",
    whatItLooksLike: "Words squish on entrance like rubber",
    description: "Classic animation principle applied to kinetic typography. Exaggerated squash on speech impact.",
    fontSize: 82,
    wordsPerGroup: 2,
    bounceScale: 35,
    yOffset: -120,
    baseColor: "#FFFFFF",
    highlightColor: "#D0BCFF",
    strokeWidth: 6,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "squash",
    previewBgGradient: "from-primary/20 via-surface-container to-transparent",
    accentBadge: "bg-primary text-on-primary",
    previewStyleClass: "preset-anim-squash",
  },
  {
    id: "drop-shadow-pop",
    num: 57,
    name: "Drop Shadow Pop",
    category: "TikTok / Reels / Shorts",
    tag: "HARD SHADOW",
    whatItLooksLike: "Hard offset colored shadow jumps out",
    description: "Retro comic block shadow with 45-degree offset that snaps out behind active keywords.",
    fontSize: 80,
    wordsPerGroup: 2,
    bounceScale: 24,
    yOffset: -120,
    baseColor: "#FFFFFF",
    highlightColor: "#FFE600",
    strokeWidth: 5,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "shadow-pop",
    previewBgGradient: "from-amber-400/20 via-surface-container to-transparent",
    accentBadge: "bg-amber-300 text-black",
    previewStyleClass: "preset-anim-shadow-pop",
  },
  {
    id: "wave-text",
    num: 58,
    name: "Wave Text",
    category: "TikTok / Reels / Shorts",
    tag: "SINE WAVE",
    whatItLooksLike: "Letters ripple up and down in a wave",
    description: "Continuous organic sine-wave phase oscillation across word groups for music and energetic reels.",
    fontSize: 74,
    wordsPerGroup: 3,
    bounceScale: 15,
    yOffset: -110,
    baseColor: "#E5E2E1",
    highlightColor: "#8083FF",
    strokeWidth: 4,
    strokeColor: "#131313",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "wave",
    previewBgGradient: "from-indigo-500/20 via-surface-container to-transparent",
    accentBadge: "bg-indigo-400 text-black",
    previewStyleClass: "preset-anim-wave",
  },
  {
    id: "highlighter-marker",
    num: 59,
    name: "Highlighter Marker",
    category: "TikTok / Reels / Shorts",
    tag: "EDU MARKER",
    whatItLooksLike: "Yellow marker stroke behind keywords",
    description: "StudyTok and educational explainer style with transparent neon marker ink highlighting key concepts.",
    fontSize: 75,
    wordsPerGroup: 2,
    bounceScale: 10,
    yOffset: -110,
    baseColor: "#FFFFFF",
    highlightColor: "#111111",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: false,
    font: "Arial-BoldMT",
    animMode: "marker",
    previewBgGradient: "from-yellow-300/25 via-surface-container to-transparent",
    accentBadge: "bg-yellow-300 text-black font-semibold",
    previewStyleClass: "preset-anim-marker",
  },
  {
    id: "zoom-punch-caption",
    num: 60,
    name: "Zoom Punch Caption",
    category: "TikTok / Reels / Shorts",
    tag: "PUNCH ZOOM",
    whatItLooksLike: "Camera zooms in with the word on emphasis",
    description: "High-octane impact punch scaling 140% to 100% on key verbal beats for punchlines and drops.",
    fontSize: 86,
    wordsPerGroup: 2,
    bounceScale: 40,
    yOffset: -130,
    baseColor: "#FFFFFF",
    highlightColor: "#FD5835",
    strokeWidth: 8,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "zoom-punch",
    previewBgGradient: "from-red-500/20 via-surface-container to-transparent",
    accentBadge: "bg-red-500 text-white",
    previewStyleClass: "preset-anim-zoom-punch",
  },
  {
    id: "split-color-words",
    num: 61,
    name: "Split Color Words",
    category: "TikTok / Reels / Shorts",
    tag: "DUAL TONE",
    whatItLooksLike: "Top half one color, bottom half another",
    description: "Modern sports and gaming two-tone typography with horizontal color split gradient.",
    fontSize: 82,
    wordsPerGroup: 2,
    bounceScale: 20,
    yOffset: -120,
    baseColor: "#FFFFFF",
    highlightColor: "#39FF14",
    strokeWidth: 6,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "split-color",
    previewBgGradient: "from-emerald-400/20 via-surface-container to-transparent",
    accentBadge: "bg-emerald-400 text-black",
    previewStyleClass: "preset-anim-split",
  },
  {
    id: "reddit-story-caption",
    num: 62,
    name: "Reddit Story Caption",
    category: "TikTok / Reels / Shorts",
    tag: "REDDIT BOT",
    whatItLooksLike: "Reddit post card, then word-by-word captions over gameplay",
    description: "The viral Minecraft/Subway Surfers narrative standard with crisp readability and orange accents.",
    fontSize: 70,
    wordsPerGroup: 3,
    bounceScale: 14,
    yOffset: -100,
    baseColor: "#FFFFFF",
    highlightColor: "#FF4500",
    strokeWidth: 5,
    strokeColor: "#1A1A1B",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "reddit",
    previewBgGradient: "from-orange-600/25 via-surface-container to-transparent",
    accentBadge: "bg-orange-600 text-white",
    previewStyleClass: "preset-anim-reddit",
  },
  {
    id: "tweet-screenshot-pop",
    num: 63,
    name: "Tweet Screenshot Pop",
    category: "TikTok / Reels / Shorts",
    tag: "TWEET CARD",
    whatItLooksLike: "Fake tweet card scales in",
    description: "Twitter/X verified card styling with blue badge, dark glass box, and crisp system typography.",
    fontSize: 68,
    wordsPerGroup: 3,
    bounceScale: 16,
    yOffset: -90,
    baseColor: "#E7E9EA",
    highlightColor: "#1D9BF0",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Helvetica-Bold",
    animMode: "tweet",
    previewBgGradient: "from-sky-500/20 via-surface-container to-transparent",
    accentBadge: "bg-sky-500 text-white",
    previewStyleClass: "preset-anim-tweet",
  },
  {
    id: "rainbow-cycle-word",
    num: 64,
    name: "Rainbow Cycle Word",
    category: "TikTok / Reels / Shorts",
    tag: "RGB CHROMA",
    whatItLooksLike: "Active word cycles through colors",
    description: "High-energy chromatic rainbow hue cycle animating across the currently spoken word.",
    fontSize: 80,
    wordsPerGroup: 2,
    bounceScale: 25,
    yOffset: -120,
    baseColor: "#FFFFFF",
    highlightColor: "#FF007F",
    strokeWidth: 6,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "rainbow",
    previewBgGradient: "from-pink-500/20 via-purple-500/20 to-transparent",
    accentBadge: "bg-gradient-to-r from-pink-500 to-yellow-400 text-black font-bold",
    previewStyleClass: "preset-anim-rainbow",
  },
  {
    id: "blur-background-box",
    num: 65,
    name: "Blur Background Box",
    category: "TikTok / Reels / Shorts",
    tag: "FROSTED GLASS",
    whatItLooksLike: "Frosted glass box behind the caption",
    description: "Apple-style frosted glass container with blurred backdrop and sleek white typography.",
    fontSize: 72,
    wordsPerGroup: 2,
    bounceScale: 12,
    yOffset: -110,
    baseColor: "#FFFFFF",
    highlightColor: "#C0C1FF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: false,
    font: "Helvetica-Bold",
    animMode: "blur-box",
    previewBgGradient: "from-white/10 via-surface-container to-transparent",
    accentBadge: "bg-white/20 text-white backdrop-blur",
    previewStyleClass: "preset-anim-blur-box",
  },

  // ==========================================
  // YOUTUBE (#66 - #75)
  // ==========================================
  {
    id: "progress-bar-chapter",
    num: 66,
    name: "Progress Bar Chapter",
    category: "YouTube",
    tag: "YT CHAPTER",
    whatItLooksLike: "Chapter title with a loading bar",
    description: "YouTube timeline-inspired chapter indicator with a linear progress fill track.",
    fontSize: 70,
    wordsPerGroup: 3,
    bounceScale: 8,
    yOffset: -100,
    baseColor: "#E5E2E1",
    highlightColor: "#FF0000",
    strokeWidth: 4,
    strokeColor: "#111111",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "progress-bar",
    previewBgGradient: "from-red-600/20 via-surface-container to-transparent",
    accentBadge: "bg-red-600 text-white",
    previewStyleClass: "preset-anim-progress",
  },
  {
    id: "search-bar-typing",
    num: 67,
    name: "Search Bar Typing",
    category: "YouTube",
    tag: "SEARCH PILL",
    whatItLooksLike: "Text typed into a fake Google search bar",
    description: "Interactive search box with search icon, microphone symbol, and typewriter typing cadence.",
    fontSize: 68,
    wordsPerGroup: 2,
    bounceScale: 10,
    yOffset: -110,
    baseColor: "#202124",
    highlightColor: "#4285F4",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial",
    animMode: "search-bar",
    previewBgGradient: "from-blue-500/20 via-surface-container to-transparent",
    accentBadge: "bg-blue-500 text-white",
    previewStyleClass: "preset-anim-search",
  },
  {
    id: "sticky-note-text",
    num: 68,
    name: "Sticky Note Text",
    category: "YouTube",
    tag: "POST-IT",
    whatItLooksLike: "Text on paper notes that slap on screen",
    description: "Explainer video favorite. Canary yellow sticky note with realistic slight peel tilt and marker text.",
    fontSize: 72,
    wordsPerGroup: 2,
    bounceScale: 20,
    yOffset: -120,
    baseColor: "#1C1C1E",
    highlightColor: "#D97706",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "sticky-note",
    previewBgGradient: "from-yellow-400/25 via-surface-container to-transparent",
    accentBadge: "bg-yellow-300 text-yellow-950 font-bold",
    previewStyleClass: "preset-anim-sticky",
  },
  {
    id: "newspaper-headline",
    num: 69,
    name: "Newspaper Headline",
    category: "YouTube",
    tag: "EDITORIAL",
    whatItLooksLike: "Headline zooms out of a newspaper",
    description: "Documentary and true-crime aesthetic with serif typography on newsprint texture with fast punch zoom.",
    fontSize: 74,
    wordsPerGroup: 2,
    bounceScale: 26,
    yOffset: -100,
    baseColor: "#F4F1EA",
    highlightColor: "#111111",
    strokeWidth: 2,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Georgia-Bold",
    animMode: "newspaper",
    previewBgGradient: "from-amber-200/20 via-surface-container to-transparent",
    accentBadge: "bg-amber-100 text-amber-950 font-serif font-bold",
    previewStyleClass: "preset-anim-newspaper",
  },
  {
    id: "arrow-callout-label",
    num: 70,
    name: "Arrow Callout Label",
    category: "YouTube",
    tag: "CALLOUT TAG",
    whatItLooksLike: "Arrow draws to an object, label appears",
    description: "Technical tutorial callout label with pointer line indicator pointing directly to subject focal point.",
    fontSize: 66,
    wordsPerGroup: 2,
    bounceScale: 14,
    yOffset: -80,
    baseColor: "#FFFFFF",
    highlightColor: "#00F0FF",
    strokeWidth: 3,
    strokeColor: "#0B192C",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "callout",
    previewBgGradient: "from-cyan-400/20 via-surface-container to-transparent",
    accentBadge: "bg-cyan-500 text-black",
    previewStyleClass: "preset-anim-callout",
  },
  {
    id: "tech-terminal-text",
    num: 71,
    name: "Tech Terminal Text",
    category: "YouTube",
    tag: "CODE CLI",
    whatItLooksLike: "Green monospace, code-style typing",
    description: "Cyber hacker green monospace terminal text with command-line blinking underscore prompt.",
    fontSize: 68,
    wordsPerGroup: 3,
    bounceScale: 0,
    yOffset: -110,
    baseColor: "#39FF14",
    highlightColor: "#FFFFFF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "CourierNewPS-BoldMT",
    animMode: "terminal",
    previewBgGradient: "from-green-500/20 via-surface-container to-transparent",
    accentBadge: "bg-green-500 text-black font-mono",
    previewStyleClass: "preset-anim-terminal",
  },
  {
    id: "stat-card-pop",
    num: 72,
    name: "Stat Card Pop",
    category: "YouTube",
    tag: "METRIC STAT",
    whatItLooksLike: "Big number + small label inside a card",
    description: "Finance and business video stat highlight with huge numerical emphasis and compact subtitle label.",
    fontSize: 84,
    wordsPerGroup: 2,
    bounceScale: 32,
    yOffset: -120,
    baseColor: "#E5E2E1",
    highlightColor: "#FFE600",
    strokeWidth: 6,
    strokeColor: "#1B1B1C",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "stat-card",
    previewBgGradient: "from-yellow-400/20 via-surface-container to-transparent",
    accentBadge: "bg-yellow-400 text-black",
    previewStyleClass: "preset-anim-stat",
  },
  {
    id: "list-build-up",
    num: 73,
    name: "List Build-Up",
    category: "YouTube",
    tag: "BULLET LIST",
    whatItLooksLike: "Bullet points appear one after another",
    description: "Ordered numbered points cascading downward with vertical translation and clean checks.",
    fontSize: 68,
    wordsPerGroup: 3,
    bounceScale: 10,
    yOffset: -90,
    baseColor: "#EDEDED",
    highlightColor: "#8083FF",
    strokeWidth: 3,
    strokeColor: "#111111",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "list",
    previewBgGradient: "from-primary-container/20 via-surface-container to-transparent",
    accentBadge: "bg-primary-container text-on-primary-container",
    previewStyleClass: "preset-anim-list",
  },
  {
    id: "quote-card",
    num: 74,
    name: "Quote Card",
    category: "YouTube",
    tag: "PULL QUOTE",
    whatItLooksLike: "Big quote marks + fade-in quote + author",
    description: "High-authority pull-quote card with oversized quotation marks and elegant serif typography.",
    fontSize: 66,
    wordsPerGroup: 3,
    bounceScale: 8,
    yOffset: -80,
    baseColor: "#E5E2E1",
    highlightColor: "#C0C1FF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Georgia",
    animMode: "quote",
    previewBgGradient: "from-secondary-container/20 via-surface-container to-transparent",
    accentBadge: "bg-secondary text-on-secondary",
    previewStyleClass: "preset-anim-quote",
  },
  {
    id: "timeline-year-text",
    num: 75,
    name: "Timeline Year Text",
    category: "YouTube",
    tag: "TIME AXIS",
    whatItLooksLike: "Years slide along a timeline",
    description: "Historical documentary axis with scrubbing year numbers translating along an animated horizontal track.",
    fontSize: 72,
    wordsPerGroup: 2,
    bounceScale: 15,
    yOffset: -100,
    baseColor: "#E5E2E1",
    highlightColor: "#FFB4A3",
    strokeWidth: 4,
    strokeColor: "#181818",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "timeline",
    previewBgGradient: "from-tertiary/20 via-surface-container to-transparent",
    accentBadge: "bg-tertiary text-on-tertiary",
    previewStyleClass: "preset-anim-timeline",
  },

  // ==========================================
  // AMV / EDITS (#76 - #85)
  // ==========================================
  {
    id: "echo-trail-text",
    num: 76,
    name: "Echo / Trail Text",
    category: "AMV / Edits",
    tag: "MOTION ECHO",
    whatItLooksLike: "Copies of the text trail behind motion",
    description: "Triple ghost trail copies cascading behind rapid typography movements for anime and AMV edits.",
    fontSize: 78,
    wordsPerGroup: 2,
    bounceScale: 28,
    yOffset: -120,
    baseColor: "#FFFFFF",
    highlightColor: "#D0BCFF",
    strokeWidth: 6,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "echo",
    previewBgGradient: "from-purple-500/25 via-surface-container to-transparent",
    accentBadge: "bg-purple-400 text-black",
    previewStyleClass: "preset-anim-echo",
  },
  {
    id: "camera-lens-distort",
    num: 77,
    name: "Camera Lens Distort Text",
    category: "AMV / Edits",
    tag: "LENS WARP",
    whatItLooksLike: "Text warps with lens distortion on hits",
    description: "Radial chromatic barrel distortion that warps outward on heavy bass hits and kick drums.",
    fontSize: 82,
    wordsPerGroup: 2,
    bounceScale: 36,
    yOffset: -120,
    baseColor: "#FFFFFF",
    highlightColor: "#00F0FF",
    strokeWidth: 7,
    strokeColor: "#1000A9",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "lens-distort",
    previewBgGradient: "from-blue-600/25 via-surface-container to-transparent",
    accentBadge: "bg-blue-500 text-white",
    previewStyleClass: "preset-anim-lens",
  },
  {
    id: "datamosh-text",
    num: 78,
    name: "Datamosh Text",
    category: "AMV / Edits",
    tag: "PIXEL MOSH",
    whatItLooksLike: "Text smears with pixel mosh",
    description: "Glitch video compression artifact smear with RGB displacement block shearing.",
    fontSize: 80,
    wordsPerGroup: 2,
    bounceScale: 26,
    yOffset: -115,
    baseColor: "#00FFCC",
    highlightColor: "#FF0055",
    strokeWidth: 5,
    strokeColor: "#0A0A14",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: false,
    font: "Arial-BoldMT",
    animMode: "datamosh",
    previewBgGradient: "from-emerald-400/20 via-pink-500/20 to-transparent",
    accentBadge: "bg-pink-500 text-white",
    previewStyleClass: "preset-anim-datamosh",
  },
  {
    id: "outline-pulse",
    num: 79,
    name: "Outline Pulse",
    category: "AMV / Edits",
    tag: "BEAT PULSE",
    whatItLooksLike: "Outline text pulses bigger on every beat",
    description: "Thick stroke text outline expanding rhythmically in sync with audio kick drum transients.",
    fontSize: 84,
    wordsPerGroup: 2,
    bounceScale: 34,
    yOffset: -120,
    baseColor: "#FFFFFF",
    highlightColor: "#FFE600",
    strokeWidth: 8,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "outline-pulse",
    previewBgGradient: "from-yellow-400/20 via-surface-container to-transparent",
    accentBadge: "bg-yellow-400 text-black",
    previewStyleClass: "preset-anim-pulse",
  },
  {
    id: "repeater-text-wall",
    num: 80,
    name: "Repeater Text Wall",
    category: "AMV / Edits",
    tag: "WALL REPEAT",
    whatItLooksLike: "Same word repeated in rows filling the screen",
    description: "Hypnotic multi-row text repeater wall creating a full background pattern behind the main speaker.",
    fontSize: 64,
    wordsPerGroup: 1,
    bounceScale: 20,
    yOffset: 0,
    baseColor: "#333333",
    highlightColor: "#FFFFFF",
    strokeWidth: 2,
    strokeColor: "#111111",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "repeater",
    previewBgGradient: "from-neutral-700/25 via-surface-container to-transparent",
    accentBadge: "bg-neutral-600 text-white",
    previewStyleClass: "preset-anim-repeater",
  },
  {
    id: "circle-text-rotate",
    num: 81,
    name: "Circle Text Rotate",
    category: "AMV / Edits",
    tag: "ORBIT SPHERE",
    whatItLooksLike: "Text wraps around a circle and spins",
    description: "Curved radial path text orbiting smoothly in 360-degree rotation around composition center.",
    fontSize: 66,
    wordsPerGroup: 2,
    bounceScale: 15,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#8083FF",
    strokeWidth: 4,
    strokeColor: "#1B1B1C",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "circle",
    previewBgGradient: "from-indigo-500/25 via-surface-container to-transparent",
    accentBadge: "bg-indigo-500 text-white",
    previewStyleClass: "preset-anim-circle",
  },
  {
    id: "invert-flash-text",
    num: 82,
    name: "Invert Flash Text",
    category: "AMV / Edits",
    tag: "INVERT FLASH",
    whatItLooksLike: "Colors invert on the beat with the text",
    description: "Intense black-to-white inverted flash strobe triggering in sync with key spoken phrases.",
    fontSize: 88,
    wordsPerGroup: 1,
    bounceScale: 38,
    yOffset: -120,
    baseColor: "#000000",
    highlightColor: "#FFFFFF",
    strokeWidth: 4,
    strokeColor: "#FFFFFF",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: false,
    font: "Arial-BoldMT",
    animMode: "invert",
    previewBgGradient: "from-white/30 via-black to-transparent",
    accentBadge: "bg-white text-black font-black",
    previewStyleClass: "preset-anim-invert",
  },
  {
    id: "letter-scatter",
    num: 83,
    name: "Letter Scatter",
    category: "AMV / Edits",
    tag: "PARTICLE SNAP",
    whatItLooksLike: "Letters explode apart then reassemble",
    description: "Disassembled character fragments that explosively converge together into the finished word.",
    fontSize: 78,
    wordsPerGroup: 2,
    bounceScale: 28,
    yOffset: -110,
    baseColor: "#E5E2E1",
    highlightColor: "#FD5835",
    strokeWidth: 5,
    strokeColor: "#131313",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "scatter",
    previewBgGradient: "from-orange-500/20 via-surface-container to-transparent",
    accentBadge: "bg-orange-500 text-white",
    previewStyleClass: "preset-anim-scatter",
  },
  {
    id: "scan-line-reveal",
    num: 84,
    name: "Scan Line Reveal",
    category: "AMV / Edits",
    tag: "LASER SWEEP",
    whatItLooksLike: "A light line sweeps and reveals the text",
    description: "High-tech laser horizon beam sweeping horizontally across the letters to reveal each line.",
    fontSize: 74,
    wordsPerGroup: 2,
    bounceScale: 14,
    yOffset: -110,
    baseColor: "#C7C4D7",
    highlightColor: "#00F0FF",
    strokeWidth: 4,
    strokeColor: "#001B2E",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "scanline",
    previewBgGradient: "from-cyan-400/20 via-surface-container to-transparent",
    accentBadge: "bg-cyan-400 text-black",
    previewStyleClass: "preset-anim-scanline",
  },
  {
    id: "anime-impact-frame",
    num: 85,
    name: "Anime Impact Frame Text",
    category: "AMV / Edits",
    tag: "SHONEN IMPACT",
    whatItLooksLike: "Black & white impact frame with big text",
    description: "Dramatic Japanese animation impact frame with high-contrast monochrome linework and giant lettering.",
    fontSize: 94,
    wordsPerGroup: 1,
    bounceScale: 45,
    yOffset: -130,
    baseColor: "#FFFFFF",
    highlightColor: "#FFE600",
    strokeWidth: 10,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Impact",
    animMode: "impact",
    previewBgGradient: "from-neutral-100/20 via-surface-container to-transparent",
    accentBadge: "bg-yellow-400 text-black font-black",
    previewStyleClass: "preset-anim-impact",
  },

  // ==========================================
  // MUSIC VIDEOS / LYRIC VIDEOS (#86 - #92)
  // ==========================================
  {
    id: "hologram-text",
    num: 86,
    name: "Hologram Text",
    category: "Music Videos / Lyric Videos",
    tag: "CYBER HOLO",
    whatItLooksLike: "Blue transparent flicker with scanlines",
    description: "Sci-fi holographic transparency with phosphor CRT scanlines and subtle horizontal jitter.",
    fontSize: 76,
    wordsPerGroup: 2,
    bounceScale: 16,
    yOffset: -110,
    baseColor: "#7FE5F0",
    highlightColor: "#FFFFFF",
    strokeWidth: 2,
    strokeColor: "#003B46",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "hologram",
    previewBgGradient: "from-teal-400/20 via-surface-container to-transparent",
    accentBadge: "bg-teal-400 text-black font-mono",
    previewStyleClass: "preset-anim-holo",
  },
  {
    id: "sticker-collage-lyrics",
    num: 87,
    name: "Sticker Collage Lyrics",
    category: "Music Videos / Lyric Videos",
    tag: "PUNK COLLAGE",
    whatItLooksLike: "Lyrics as cut-out paper letters",
    description: "Ransom note punk magazine collage with mixed colored backgrounds and varying tilted angles.",
    fontSize: 76,
    wordsPerGroup: 2,
    bounceScale: 25,
    yOffset: -120,
    baseColor: "#000000",
    highlightColor: "#FFFFFF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "collage",
    previewBgGradient: "from-amber-300/20 via-surface-container to-transparent",
    accentBadge: "bg-yellow-300 text-black font-bold",
    previewStyleClass: "preset-anim-collage",
  },
  {
    id: "graffiti-spray-text",
    num: 88,
    name: "Graffiti Spray Text",
    category: "Music Videos / Lyric Videos",
    tag: "STREET SPRAY",
    whatItLooksLike: "Text sprays on a wall",
    description: "Urban street aerosol spray texture with paint drip accents for rap and hip-hop lyric videos.",
    fontSize: 82,
    wordsPerGroup: 2,
    bounceScale: 24,
    yOffset: -110,
    baseColor: "#FFFFFF",
    highlightColor: "#FF007F",
    strokeWidth: 7,
    strokeColor: "#111111",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "graffiti",
    previewBgGradient: "from-pink-600/20 via-surface-container to-transparent",
    accentBadge: "bg-pink-600 text-white font-bold",
    previewStyleClass: "preset-anim-graffiti",
  },
  {
    id: "smoke-reveal-text",
    num: 89,
    name: "Smoke Reveal Text",
    category: "Music Videos / Lyric Videos",
    tag: "MIST DISSIPATE",
    whatItLooksLike: "Text appears out of smoke",
    description: "Atmospheric cloud mist dissipation revealing ethereal luminous glowing typography.",
    fontSize: 74,
    wordsPerGroup: 2,
    bounceScale: 10,
    yOffset: -100,
    baseColor: "#E5E2E1",
    highlightColor: "#C0C1FF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Helvetica-Bold",
    animMode: "smoke",
    previewBgGradient: "from-slate-400/20 via-surface-container to-transparent",
    accentBadge: "bg-slate-300 text-black",
    previewStyleClass: "preset-anim-smoke",
  },
  {
    id: "mirror-reflection-text",
    num: 90,
    name: "Mirror Reflection Text",
    category: "Music Videos / Lyric Videos",
    tag: "FLOOR GLOSS",
    whatItLooksLike: "Text with reflection underneath",
    description: "Sleek glossy showroom floor reflection with vertical inverted opacity gradient under each word.",
    fontSize: 76,
    wordsPerGroup: 2,
    bounceScale: 15,
    yOffset: -130,
    baseColor: "#FFFFFF",
    highlightColor: "#D0BCFF",
    strokeWidth: 4,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "mirror",
    previewBgGradient: "from-indigo-400/20 via-surface-container to-transparent",
    accentBadge: "bg-indigo-300 text-black",
    previewStyleClass: "preset-anim-mirror",
  },
  {
    id: "word-rain",
    num: 91,
    name: "Word Rain",
    category: "Music Videos / Lyric Videos",
    tag: "RAIN FALL",
    whatItLooksLike: "Words fall from the top like rain",
    description: "Smooth vertical cascading gravity drop with motion blur trailing for emotional ballads and lo-fi tracks.",
    fontSize: 70,
    wordsPerGroup: 2,
    bounceScale: 12,
    yOffset: -80,
    baseColor: "#B0C4DE",
    highlightColor: "#FFFFFF",
    strokeWidth: 3,
    strokeColor: "#0D1B2A",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "rain",
    previewBgGradient: "from-sky-600/20 via-surface-container to-transparent",
    accentBadge: "bg-sky-400 text-black",
    previewStyleClass: "preset-anim-rain",
  },
  {
    id: "pixel-sort-text",
    num: 92,
    name: "Pixel Sort Text",
    category: "Music Videos / Lyric Videos",
    tag: "STREAK GLITCH",
    whatItLooksLike: "Glitchy pixel-sorted stretches",
    description: "Vertical luminance sorting artifact stretches creating organic digital streaks on transients.",
    fontSize: 78,
    wordsPerGroup: 2,
    bounceScale: 20,
    yOffset: -110,
    baseColor: "#FFFFFF",
    highlightColor: "#FF007F",
    strokeWidth: 4,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: false,
    font: "Arial-BoldMT",
    animMode: "pixel-sort",
    previewBgGradient: "from-rose-500/20 via-surface-container to-transparent",
    accentBadge: "bg-rose-500 text-white",
    previewStyleClass: "preset-anim-pixel-sort",
  },

  // ==========================================
  // STORYTELLING & MOVIE (#93 - #100)
  // ==========================================
  {
    id: "star-wars-crawl",
    num: 93,
    name: "Star Wars Crawl",
    category: "Storytelling & Movie",
    tag: "SPACE CRAWL",
    whatItLooksLike: "Text scrolls into the distance in perspective",
    description: "Iconic cinematic 3D perspective scroll angling back into deep space with warm yellow typography.",
    fontSize: 66,
    wordsPerGroup: 3,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFE81F",
    highlightColor: "#FFFFFF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: false,
    pop: false,
    shadow: false,
    font: "Arial-BoldMT",
    animMode: "crawl",
    previewBgGradient: "from-yellow-400/20 via-black to-transparent",
    accentBadge: "bg-yellow-400 text-black font-bold",
    previewStyleClass: "preset-anim-crawl",
  },
  {
    id: "location-stamp",
    num: 94,
    name: "Location Stamp",
    category: "Storytelling & Movie",
    tag: "GEO TELESCRIPT",
    whatItLooksLike: "\"PARIS, 1998\" typed in the corner",
    description: "Espionage and thriller film location tele-type stamp with blinking cursor and letterbox framing.",
    fontSize: 62,
    wordsPerGroup: 2,
    bounceScale: 0,
    yOffset: -40,
    baseColor: "#E5E2E1",
    highlightColor: "#FFFFFF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: false,
    pop: false,
    shadow: true,
    font: "CourierNewPS-BoldMT",
    animMode: "stamp",
    previewBgGradient: "from-neutral-600/20 via-surface-container to-transparent",
    accentBadge: "bg-neutral-600 text-white font-mono",
    previewStyleClass: "preset-anim-stamp",
  },
  {
    id: "chapter-card",
    num: 95,
    name: "Chapter Card",
    category: "Storytelling & Movie",
    tag: "ROMAN CHAPTER",
    whatItLooksLike: "Black screen, \"Chapter 1\" fades in",
    description: "Moody art-house cinema chapter separator with generous tracking and slow serene dissolve.",
    fontSize: 70,
    wordsPerGroup: 2,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#EDEDED",
    highlightColor: "#C0C1FF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: false,
    font: "Georgia",
    animMode: "chapter",
    previewBgGradient: "from-slate-800/40 via-surface-container to-transparent",
    accentBadge: "bg-slate-700 text-white font-serif",
    previewStyleClass: "preset-anim-chapter",
  },
  {
    id: "credits-roll",
    num: 96,
    name: "Credits Roll",
    category: "Storytelling & Movie",
    tag: "FILM CREDITS",
    whatItLooksLike: "Classic vertical scroll",
    description: "Hollywood feature film closing credit scroll with perfectly smooth continuous linear vertical velocity.",
    fontSize: 60,
    wordsPerGroup: 3,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#E5E2E1",
    highlightColor: "#FFFFFF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: false,
    highlight: false,
    pop: false,
    shadow: false,
    font: "Helvetica",
    animMode: "credits",
    previewBgGradient: "from-zinc-700/20 via-surface-container to-transparent",
    accentBadge: "bg-zinc-600 text-white",
    previewStyleClass: "preset-anim-credits",
  },
  {
    id: "inner-thought-text",
    num: 97,
    name: "Inner Thought Text",
    category: "Storytelling & Movie",
    tag: "DREAM WHISPER",
    whatItLooksLike: "Italic, faded, floating near the character",
    description: "Internal protagonist monologue with italic slant, gentle ethereal float, and soft luminance.",
    fontSize: 66,
    wordsPerGroup: 3,
    bounceScale: 8,
    yOffset: -70,
    baseColor: "#D1D5DB",
    highlightColor: "#D0BCFF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Georgia-Italic",
    animMode: "thought",
    previewBgGradient: "from-purple-900/25 via-surface-container to-transparent",
    accentBadge: "bg-purple-900/60 text-purple-200 font-serif italic",
    previewStyleClass: "preset-anim-thought",
  },
  {
    id: "letter-diary-text",
    num: 98,
    name: "Letter / Diary Text",
    category: "Storytelling & Movie",
    tag: "PARCHMENT SCRIPT",
    whatItLooksLike: "Handwritten text on paper with voiceover",
    description: "Memoir and period film handwritten script with organic letter pacing and antique ink warmth.",
    fontSize: 68,
    wordsPerGroup: 2,
    bounceScale: 10,
    yOffset: -90,
    baseColor: "#3D2B1F",
    highlightColor: "#6B4423",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: false,
    font: "Georgia",
    animMode: "diary",
    previewBgGradient: "from-amber-200/30 via-surface-container to-transparent",
    accentBadge: "bg-amber-800 text-amber-100 font-serif",
    previewStyleClass: "preset-anim-diary",
  },
  {
    id: "time-skip-title",
    num: 99,
    name: "Time Skip Title",
    category: "Storytelling & Movie",
    tag: "TIME JUMP",
    whatItLooksLike: "\"3 YEARS LATER\" with a whoosh",
    description: "Impact transition title card for time lapses, era changes, and dramatic narrative jumps.",
    fontSize: 84,
    wordsPerGroup: 2,
    bounceScale: 30,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FFE600",
    strokeWidth: 6,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "time-skip",
    previewBgGradient: "from-neutral-200/25 via-surface-container to-transparent",
    accentBadge: "bg-white text-black font-black",
    previewStyleClass: "preset-anim-time-skip",
  },
  {
    id: "wes-anderson-title",
    num: 100,
    name: "Wes Anderson Title",
    category: "Storytelling & Movie",
    tag: "PASTEL FUTURA",
    whatItLooksLike: "Centered Futura, symmetrical, pastel background",
    description: "Whimsical auteur cinema with perfectly centered yellow Futura, wide tracking, and pastel color harmony.",
    fontSize: 72,
    wordsPerGroup: 2,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFD166",
    highlightColor: "#EF476F",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: false,
    font: "Futura-Bold",
    animMode: "wes-anderson",
    previewBgGradient: "from-yellow-200/25 via-pink-300/15 to-transparent",
    accentBadge: "bg-yellow-400 text-neutral-900 font-bold",
    previewStyleClass: "preset-anim-wes-anderson",
  },
];

/** Kinetic Motion: one preset per After Effects motion type (see shared/motion.ts). */
const KINETIC_PRESETS: ViralPreset[] = [
  {
    id: "slide-up-stack",
    num: 101,
    name: "Slide Up Stack",
    category: "Kinetic Motion",
    tag: "RISE",
    whatItLooksLike: "Each word glides up into place",
    description: "Words rise from below as they're spoken. Clean, modern and easy to read at any pace.",
    fontSize: 78,
    wordsPerGroup: 2,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#3DDCFF",
    strokeWidth: 6,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-Black",
    animMode: "motion:slide-up",
    previewBgGradient: "from-cyan-400/20 via-surface-container to-transparent",
    accentBadge: "bg-cyan-300 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "drop-zone",
    num: 102,
    name: "Drop Zone",
    category: "Kinetic Motion",
    tag: "GRAVITY",
    whatItLooksLike: "Words fall in from above",
    description: "Every word drops onto the line with a heavy landing. Great for hype edits and punchlines.",
    fontSize: 92,
    wordsPerGroup: 1,
    bounceScale: 18,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FF8A00",
    strokeWidth: 8,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Impact",
    animMode: "motion:drop-in",
    previewBgGradient: "from-orange-500/20 via-surface-container to-transparent",
    accentBadge: "bg-orange-400 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "side-swipe",
    num: 103,
    name: "Side Swipe",
    category: "Kinetic Motion",
    tag: "SWIPE",
    whatItLooksLike: "Words slide in from the side",
    description: "Horizontal slide-in per word for talking-head and explainer content.",
    fontSize: 70,
    wordsPerGroup: 3,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#7CFF6B",
    strokeWidth: 5,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Verdana-Bold",
    animMode: "motion:slide-left",
    previewBgGradient: "from-lime-400/20 via-surface-container to-transparent",
    accentBadge: "bg-lime-300 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "grow-pop",
    num: 104,
    name: "Grow Pop",
    category: "Kinetic Motion",
    tag: "GROW",
    whatItLooksLike: "Words grow from nothing",
    description: "Each word scales up from zero with a snappy ease. Playful and bold.",
    fontSize: 88,
    wordsPerGroup: 1,
    bounceScale: 20,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FFE600",
    strokeWidth: 8,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-Black",
    animMode: "motion:zoom-in",
    previewBgGradient: "from-yellow-400/20 via-surface-container to-transparent",
    accentBadge: "bg-yellow-300 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "slam-cut",
    num: 105,
    name: "Slam Cut",
    category: "Kinetic Motion",
    tag: "SLAM",
    whatItLooksLike: "Oversized words slam down to size",
    description: "Words start huge and slam into place. Maximum impact for one-word beats.",
    fontSize: 96,
    wordsPerGroup: 1,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FF3B3B",
    strokeWidth: 10,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Impact",
    animMode: "motion:zoom-out",
    previewBgGradient: "from-red-600/25 via-surface-container to-transparent",
    accentBadge: "bg-red-500 text-white",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "focus-pull",
    num: 106,
    name: "Focus Pull",
    category: "Kinetic Motion",
    tag: "RACK FOCUS",
    whatItLooksLike: "Blurry words sharpen into focus",
    description: "Cinematic rack-focus reveal. Suits documentaries, trailers and moody edits.",
    fontSize: 72,
    wordsPerGroup: 2,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#F5F1E8",
    highlightColor: "#E6C38A",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Georgia-Bold",
    animMode: "motion:blur-in",
    previewBgGradient: "from-amber-200/15 via-surface-container to-transparent",
    accentBadge: "bg-amber-200 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "letter-spread",
    num: 107,
    name: "Letter Spread",
    category: "Kinetic Motion",
    tag: "TRACKING",
    whatItLooksLike: "Letters start wide, then tighten",
    description: "Letters collapse from wide spacing into the word. Elegant for music and fashion.",
    fontSize: 68,
    wordsPerGroup: 2,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#C9A7FF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "TrebuchetMS-Bold",
    animMode: "motion:tracking",
    previewBgGradient: "from-violet-400/20 via-surface-container to-transparent",
    accentBadge: "bg-violet-300 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "skew-swipe",
    num: 108,
    name: "Skew Swipe",
    category: "Kinetic Motion",
    tag: "SPEED",
    whatItLooksLike: "Italic-slanted words snap straight",
    description: "Words enter slanted and snap upright, like motion blur on a whip pan.",
    fontSize: 80,
    wordsPerGroup: 2,
    bounceScale: 12,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#00F0FF",
    strokeWidth: 6,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Arial-BoldItalicMT",
    animMode: "motion:skew",
    previewBgGradient: "from-sky-400/20 via-surface-container to-transparent",
    accentBadge: "bg-sky-300 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "spin-in",
    num: 109,
    name: "Spin In",
    category: "Kinetic Motion",
    tag: "ROTATE 360",
    whatItLooksLike: "Words spin a full turn into place",
    description: "A full rotation per word for energetic, game-show style captions.",
    fontSize: 84,
    wordsPerGroup: 1,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FF4FD8",
    strokeWidth: 8,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-Black",
    animMode: "motion:spin",
    previewBgGradient: "from-fuchsia-500/20 via-surface-container to-transparent",
    accentBadge: "bg-fuchsia-400 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "hype-shake",
    num: 110,
    name: "Hype Shake",
    category: "Kinetic Motion",
    tag: "SHAKE",
    whatItLooksLike: "Words shake as they land",
    description: "A quick decaying shake on every word. Built for reactions, gaming and hype.",
    fontSize: 90,
    wordsPerGroup: 1,
    bounceScale: 25,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FF2E2E",
    strokeWidth: 10,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Impact",
    animMode: "motion:shake",
    previewBgGradient: "from-red-500/25 via-surface-container to-transparent",
    accentBadge: "bg-red-500 text-white",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "soft-documentary",
    num: 111,
    name: "Soft Documentary",
    category: "Kinetic Motion",
    tag: "SUBTLE",
    whatItLooksLike: "Gentle fade-in, lower third",
    description: "Understated fade-ins in the lower third for interviews and documentaries.",
    fontSize: 56,
    wordsPerGroup: 3,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FFFFFF",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: false,
    pop: false,
    shadow: true,
    font: "Georgia",
    animMode: "motion:fade",
    previewBgGradient: "from-neutral-300/15 via-surface-container to-transparent",
    accentBadge: "bg-neutral-200 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "wave-chorus",
    num: 112,
    name: "Wave Chorus",
    category: "Kinetic Motion",
    tag: "LYRIC WAVE",
    whatItLooksLike: "Words bob on a gentle wave",
    description: "A continuous wave across the line for lyric videos and choruses.",
    fontSize: 74,
    wordsPerGroup: 3,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FFB3F0",
    strokeWidth: 4,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "TrebuchetMS-Bold",
    animMode: "motion:wave",
    previewBgGradient: "from-pink-400/20 via-surface-container to-transparent",
    accentBadge: "bg-pink-300 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "tilt-talk",
    num: 113,
    name: "Tilt Talk",
    category: "Kinetic Motion",
    tag: "TILT",
    whatItLooksLike: "Words tilt in with a small overshoot",
    description: "A light rotation per word that keeps podcasts and vlogs lively.",
    fontSize: 72,
    wordsPerGroup: 2,
    bounceScale: 14,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FFD23F",
    strokeWidth: 6,
    strokeColor: "#000000",
    posIndex: 1,
    reveal: true,
    highlight: true,
    pop: true,
    shadow: true,
    font: "Verdana-Bold",
    animMode: "motion:rotate",
    previewBgGradient: "from-yellow-300/20 via-surface-container to-transparent",
    accentBadge: "bg-yellow-300 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "rubber-word",
    num: 114,
    name: "Rubber Word",
    category: "Kinetic Motion",
    tag: "RUBBER",
    whatItLooksLike: "Words squash and stretch",
    description: "Cartoon squash-and-stretch on every word. Fun for kids and comedy content.",
    fontSize: 86,
    wordsPerGroup: 1,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#6BFF95",
    strokeWidth: 8,
    strokeColor: "#000000",
    posIndex: 2,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-Black",
    animMode: "motion:squash",
    previewBgGradient: "from-emerald-400/20 via-surface-container to-transparent",
    accentBadge: "bg-emerald-300 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "mono-fade",
    num: 115,
    name: "Mono Fade",
    category: "Kinetic Motion",
    tag: "CODE",
    whatItLooksLike: "Monospace words fade in",
    description: "Monospaced captions that fade in word by word. Ideal for tech and coding videos.",
    fontSize: 60,
    wordsPerGroup: 3,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#E8FFE8",
    highlightColor: "#3DFF7A",
    strokeWidth: 0,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "CourierNewPS-BoldMT",
    animMode: "motion:fade",
    previewBgGradient: "from-green-500/20 via-surface-container to-transparent",
    accentBadge: "bg-green-400 text-black",
    previewStyleClass: "preset-anim-motion",
  },
  {
    id: "clean-cut",
    num: 116,
    name: "Clean Cut",
    category: "Kinetic Motion",
    tag: "MINIMAL",
    whatItLooksLike: "Plain hard-cut captions",
    description: "No motion at all: words appear exactly on time. The safest choice for long-form content.",
    fontSize: 60,
    wordsPerGroup: 3,
    bounceScale: 0,
    yOffset: 0,
    baseColor: "#FFFFFF",
    highlightColor: "#FFE600",
    strokeWidth: 4,
    strokeColor: "#000000",
    posIndex: 0,
    reveal: true,
    highlight: true,
    pop: false,
    shadow: true,
    font: "Arial-BoldMT",
    animMode: "motion:none",
    previewBgGradient: "from-neutral-400/15 via-surface-container to-transparent",
    accentBadge: "bg-white text-black",
    previewStyleClass: "preset-anim-motion",
  },
];

export const VIRAL_PRESETS: ViralPreset[] = [...CLASSIC_PRESETS, ...KINETIC_PRESETS];
